### ISSUE TITLE
Ignores halting conditions

### ISSUE THREAD

**Issue by AndBM** [michaelhush/M-LOOP#13]
While testing M-LOOP by manually deleting _exp_input_ and creating _exp_output.txt_, using the simple configuration

`num_params = 2;
max_num_runs = 3`

I was unable to get the program to stop. Using configuration

`num_params = 2;
max_num_runs = 3;
target_cost = 0.1`

it ends seemingly at random, both running more than three times, and continuing past costs < 0.1. See attached file for an example of behaviour with the second configuration. 
[strange_output.txt](https://github.com/michaelhush/M-LOOP/files/558313/strange_output.txt)

Is it not supposed to stop before 7 runs, or at the instant it surpasses target_cost?

I'm running on Linux Mint.

**Comment by michaelhush** [comment]
It should not behave like that in principle. I'll try and reproduce the problem.

**Comment by michaelhush** [comment]
This has been fixed as of #14 

M-LOOP now halts immediately when any of the conditions are met. Unit tests have been added to the automated tests to avoid this problem in future updates.

Previously M-LOOP was programmed to complete a set of training runs for the learner before it would check if the max number of runs was met. This lead to this inconsistent behavior.

I'm going to close this issue. Let me know if you're still seeing the same problem with the latest version in the master branch.

**Comment by AndBM** [comment]
After running `git pull origin master`, the problem persists. It exits immediately on reaching target cost, but ignores maximum runs.

Is this only an issue when I do very few runs? Will it work for larger values of maximum runs?

**Comment by michaelhush** [comment]
How many runs are you doing? Currently I think there will be issues if it only computes one run. But more than one and in principle it should work. I'll look into it again. The new test cases I put in must not be covering your particular issue. Can you send me your test output like you did before. 

Thanks for checking again.

**Comment by AndBM** [comment]
With the same config, max 3 runs, target cost 0.1:

[output1.txt](https://github.com/michaelhush/M-LOOP/files/582753/output1.txt)

When I only do the "max 5 runs" condition, it stopped after 10 runs. Is this some kind of minimum still there?

[output2.txt](https://github.com/michaelhush/M-LOOP/files/582754/output2.txt)

As mentioned first, this is just manual testing to understand the program. Final use might very well go beyond 10 iterations.

**Comment by michaelhush** [comment]
I can't replicate the behavior. Can you send me the config file as well?

Can you also run another test for me? Go into the install folder for mloop there should be a file called setup.py run the following from the command line:

python setup.py test

This should run 18 tests, that include extra tests checking for the situation you described. 

How did you install M-LOOP as well? Did you use python setup.py develop or install. If you used install you will have to run the installation again after pulling the latest copy from the github.

It's always better to fix these small things. But in any case, after you go after 10 iterations things should all work correctly, no matter what version you are using.

Thanks again for your help looking into this.

**Comment by AndBM** [comment]
Hi again, sorry about the long wait. I decided it was a minor issue and continued my project, but now I've done as you asked me. My config file is literally just (two lines)

`num_params = 2; max_num_runs = 2`

Running the test runs 18 test as expected. I installed using develop, I followed the installation instructions in the documentation.

It still doesn't appear to run less than 10 iterations. Upon installation I first accidentally installed using `sudo`, but then re-installed as user. I don't know if this might have caused any problems?

**Comment by michaelhush** [comment]
Thanks, I'll continue doing some testing. 

It is possible that by using sudo you may have installed an older version into the python distribution you're using by default. The user installation may not be the one you are running. Even if it runs the 18 tests as expected, this may still be the case.

To check this, start a python session then use the commands:
`import mloop as mp` 
`print(mp.__version__)`


This should print "2.1.1" if you're running the latest version from the github. If it's something older the sudo vs user installation may be the problem.

**Comment by AndBM** [comment]
Doing your check returns "2.1.0", so we seem to have found the issue. I'll look into fixing it.

**Comment by AndBM** [comment]
The issue has not been resolved. It still stops after 10 runs, even though I have specified maximum 3 runs. This is probably not relevant if your program needs a minimum of 10 runs.

**Comment by michaelhush** [comment]
Great. Let me know if that fixes it. I'll add you to the contributors page for the documentation as well.
